CREATE OR REPLACE FUNCTION GETPARCELASSETOR(
	IDSECT IN SECTORREGA.SECTORID%TYPE
) RETURN SYS_REFCURSOR IS
	LISTA SYS_REFCURSOR;
BEGIN
	OPEN LISTA FOR
		SELECT
			DISTINCT NOMEPARCELA
		FROM
			SECTOR_CULTURAINSTALADA
		WHERE
			SECTORID = IDSECT;
	RETURN LISTA;
END;
/

CREATE OR REPLACE FUNCTION NOVOIDOPERACAO RETURN NUMBER AS
	NEWIDOPERATION NUMBER;
BEGIN
	SELECT
		NVL(MAX(OPERACAOID), 0) + 1 INTO NEWIDOPERATION
	FROM
		OPERACAO;
	RETURN NEWIDOPERATION;
END;
/

CREATE OR REPLACE FUNCTION REGISTARREGA(
	IDSECT IN SECTORREGA.SECTORID%TYPE,
	DATAOP IN OPERACAO.DIAOPERACAO%TYPE,
	QTD IN OPERACAO.QUANTIDADE%TYPE
) RETURN BOOLEAN IS
	OPID        NUMBER := 0;
	PARCELANOME VARCHAR2(50);
	LISTA       SYS_REFCURSOR;
BEGIN
	LISTA := GETPARCELASSETOR(IDSECT);
	LOOP
		FETCH LISTA INTO PARCELANOME;
		OPID := NOVOIDOPERACAO();
		EXIT WHEN LISTA%NOTFOUND;
		INSERT INTO OPERACAO(
			OPERACAOID,
			QUANTIDADE,
			DIAOPERACAO,
			DATAREGISTO,
			TIPOUNIDADE,
			TIPOOPERACAO,
			NOMEESTADOOPERACAO
		) VALUES(
			OPID,
			QTD,
			DATAOP,
			DATAOP,
			'min',
			'Rega',
			'Pendente'
		);
	END LOOP;

	CLOSE LISTA;
	RETURN TRUE;
END;
/

-- bloco teste

SET SERVEROUTPUT ON;

DECLARE
	VIDSECT SECTORREGA.SECTORID%TYPE := '10';
	VDATAOP OPERACAO.DIAOPERACAO%TYPE := TO_DATE('2023-01-02', 'YYYY-MM-DD');
	VQTD    OPERACAO.QUANTIDADE%TYPE := 10;
BEGIN
	IF REGISTARREGA(VIDSECT, VDATAOP, VQTD) THEN
		DBMS_OUTPUT.PUT_LINE('Rega successfully registered.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('Failed to register rega.');
	END IF;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('An error occurred: '
		                     || SQLERRM);
END;
/