CREATE OR REPLACE FUNCTION GETPARCELASSETOR(
	IDSECT IN SECTORREGA.SECTORID%TYPE
) RETURN SYS_REFCURSOR IS
	LISTA SYS_REFCURSOR;
BEGIN
	OPEN LISTA FOR
		SELECT
			DISTINCT NOMEPARCELA
		FROM
			SECTOR_CULTURAINSTALADA
		WHERE
			SECTORID = IDSECT;
	RETURN LISTA;
END;
/

CREATE OR REPLACE FUNCTION NOVOIDOPERACAO RETURN NUMBER AS
	NEWIDOPERATION NUMBER;
BEGIN
	SELECT
		NVL(MAX(OPERACAOID), 0) + 1 INTO NEWIDOPERATION
	FROM
		OPERACAO;
	RETURN NEWIDOPERATION;
END;
/

CREATE OR REPLACE FUNCTION REGISTARFERTIRREGA(
	IDSECT IN SECTORREGA.SECTORID%TYPE,
	DATAOP IN OPERACAO.DIAOPERACAO%TYPE,
	QTD IN OPERACAO.QUANTIDADE%TYPE,
	MIXID IN MIXFERTIRREGA.IDMIX%TYPE
) RETURN BOOLEAN IS
	OPID        NUMBER := 0;
	PARCELANOME VARCHAR2(50);
	LISTA       SYS_REFCURSOR;
BEGIN
	LISTA := GETPARCELASSETOR(IDSECT);
	LOOP
		FETCH LISTA INTO PARCELANOME;
		OPID := NOVOIDOPERACAO();
		EXIT WHEN LISTA%NOTFOUND;
		INSERT INTO OPERACAO(
			OPERACAOID,
			QUANTIDADE,
			DIAOPERACAO,
			DATAREGISTO,
			TIPOUNIDADE,
			TIPOOPERACAO,
			NOMEESTADOOPERACAO
		) VALUES(
			OPID,
			QTD,
			DATAOP,
			DATAOP,
			'min',
			'Rega',
			'Pendente'
		);
		INSERT INTO FERTIRREGA(
			OPERACAOID,
			IDMIX
		) VALUES(
			OPID,
			MIXID
		);
	END LOOP;

	CLOSE LISTA;
	RETURN TRUE;
END;
/
