CREATE OR REPLACE TRIGGER TRGDELETELOG BEFORE
	DELETE ON HISTORIALOPERACOES
BEGIN
	RAISE_APPLICATION_ERROR(-20001, 'Logs nao podem ser apagados');
END;
/

-- Blocos Anónimos --
DECLARE
BEGIN
	DELETE FROM HISTORIALOPERACOES
	WHERE
		IDLOG = 1;
END;
/